### ISSUE TITLE
Question: How to keystroke <- and %>% ?

### ISSUE THREAD

**Issue by hugeme** [holgerbrandl/r4intellij#181]
hi @holgerbrandl thank you for providing that integration with pycharm/intellij and R. I have a quite basic question I could not find any reference. Without assigning or redefining the current key bindings, is there anything similar to  `alt` and `-` to get the assignment operator `<-`? Similarly, how would you keystroke the pipe - operator `%>% ` (mac)?

**Comment by holgerbrandl** [comment]
You could just use a livetemplate. The plugin is declaring a few automatically, and maybe we could add ` <-` and `%>%` as well (via PR if possible, since I don't have much time at the moment). See https://github.com/holgerbrandl/r4intellij/blob/master/resources/liveTemplates/rtemplates.xml

Btw most R folks seem to consider `=` to be preferrable to `<-` these days. See https://stackoverflow.com/a/1742591/590437

**Comment by hugeme** [comment]
@holgerbrandl @jewellsean thank you! I think about adding that via PR in future.
