### ISSUE TITLE
EOL expected error

### ISSUE THREAD

**Issue by andytompkins** [holgerbrandl/r4intellij#36]
I am trying to bring some R code from my organization into R4Intellij to evaluate. The programmer has written something like this

something <- function(x) {
    optionalInput <- c(
    )
}

This causes the error EOL expected, got '' (shown on the top line). If I put the closing paren on the same line as the 'c(' I get the expected behavior. There is other code in the function that may be confusing the issue, in a trivial example the error shows up in an expected place (though R still thinks the code is fine with the line break).

**Comment by holgerbrandl** [comment]
I agree it should be more robust against line breaks. I'll have a look.

Showing the errors at the right place often goes wrong at the moment, but is hard to fix for me. This is because if the parser fails to read some element (like a function definition), the error is reported for this top-level element and not in the line where the problem actually occurs.
