### ISSUE TITLE
generated _RLexer doesn't build

### ISSUE THREAD

**Issue by avisser** [holgerbrandl/r4intellij#65]
Hi Holger,

I'm interested in contributing to this plugin. I love R and IntelliJ.

However, I checked out Master and have hit some issues:
* /misc/JFlex/JFlex.jar was missing
 * I downloaded 1.6.1 to move on
* Ant task create_flex4r then didn't work
 * I commented out `<arg value="--charat"/>` to move on
* Now, the new _RLexer.java doesn't build

Can you advise on how to get up and running with the plugin?

-Andy

**Comment by holgerbrandl** [comment]
Hey Andy, thanks for interest in r4intellij.

I do it as follows.
1) Install jflex plugin in Intellij
2) Restart Intellij. Now there's a new menu entry to rerun the lexer generation
![image](https://cloud.githubusercontent.com/assets/200952/13319394/b0771b2e-dbc1-11e5-8fc2-1170af4a190e.png)
3) Somehow the  import `import com.r4intellij.psi.RTypes;`
is missing in the generated `com.r4intellij.lang.lexer._RLexer`, which I add manually.

The jflex plugin somehow picks up the lexer-build config from ./build.xml.

I'm aware that having a proper build-script for creating the lexer would be better. However, since I hardly ever had to change the lexer code, it worked well so far using the clicky-clicky method described above.

-H

**Comment by avisser** [comment]
Believe it or not, the secret is that comment at the top of _RLexer.java in the background of your screenshot. I found a copy of JFlex.jar from the Intelli-arc project on com.google.com. That version of jflex accepts the option `-charat` which was need to get everything working. [Link to jar](https://github.com/avisser/intelli-arc/blob/master/lib/JFlex.jar)

I've now starting playing around with rebuilding the grammar. Which .bnf file are you currently using?

-Andy

**Comment by holgerbrandl** [comment]
You're right, I was not using the JFlex plugin but simply ant. I thought that JFlex.jar would be part of the repo, but the used .gitignore prevented it. I've bundled it with f90360cf641a527c9ecfd8fbfc71bb701cf9aea7.

I'm using `gramgen/RGrammar.bnf`. To build it I'm using the IJ plugin 'Grammar-Kit'. It adds a menu entry named `Generate Parser Code` 
![image](https://cloud.githubusercontent.com/assets/200952/13388670/28a4fee2-dec2-11e5-800a-c870e5550b10.png)
if the bnf file has the focus. Running it will recreate all the code under `gen`
